version: 2

jobs:
  test:
    docker:
      - image: continuumio/miniconda3:latest

    steps:
      - checkout
      - run:
          name: install requirements
          command: |
            conda env create -p httoolsenv --file requirements-linux.yaml
      - run:
          name: run test
          command: |
            conda activate httoolsenv/ && \
            bash test_snakemake.sh
workflows:
  version: 2
  test:
    jobs:
      - test
