version: 2

jobs:
  test:
    docker:
      - image: continuumio/miniconda3:latest

    steps:
      - checkout
      - run:
          name: install requirements
          command: |
            conda env create -p httoolsenv --file requirements-linux.yaml && \
            source activate httoolsenv/
      - run:
          name: run test
          command: bash test_snakemake.sh
workflows:
  version: 2
  test:
    jobs:
      - test
